spring:
  main:
    web-application-type: none
  application:
    name: circuit-breaker
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
resilience4j.circuitbreaker:
    instances:
      distributor-network:
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 60
        wait-duration-in-open-state:
          seconds: 10
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 3

#          configuraton Approach